/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author patil
 */
import java.sql.*;
import javax.swing.*;               
import java.text.ParseException;       // For handling date parsing errors
import java.text.SimpleDateFormat;     // For date parsing
import javax.swing.JOptionPane;        // For showing message dialogs



public class Add_Employee extends javax.swing.JFrame {

    /**
     * Creates new form Add_Employee
     */
    
    public Add_Employee() {
        initComponents();
        
         setDefaultCloseOperation(Add_Employee.DISPOSE_ON_CLOSE);
         update = new javax.swing.JButton();
         update.setText("UPDATE");
         update.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        updateActionPerformed(evt);
    }
});
         delete = new javax.swing.JButton();
delete.setText("DELETE");
delete.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        deleteActionPerformed(evt);
    }
});


    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        empid = new javax.swing.JButton();
        empname = new javax.swing.JButton();
        contactno = new javax.swing.JButton();
        age = new javax.swing.JButton();
        gender = new javax.swing.JButton();
        empaddress = new javax.swing.JButton();
        empemail = new javax.swing.JButton();
        hiredate = new javax.swing.JButton();
        jobposition = new javax.swing.JButton();
        salary = new javax.swing.JButton();
        stationid = new javax.swing.JButton();
        add = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        t11 = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        empid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        empid.setText("EMP ID");

        empname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        empname.setText("EMP NAME");

        contactno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        contactno.setText("CONTACT NO");
        contactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnoActionPerformed(evt);
            }
        });

        age.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        age.setText("AGE");

        gender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gender.setText("GENDER");

        empaddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        empaddress.setText("EMP ADDRESS");

        empemail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        empemail.setText("EMP EMAIL");

        hiredate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hiredate.setText("HIRE DATE");

        jobposition.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jobposition.setText("JOB POSITION");

        salary.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        salary.setText("SALARY");

        stationid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        stationid.setText("STATION ID");

        add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });

        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });

        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });

        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });

        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });

        t10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t10ActionPerformed(evt);
            }
        });

        t11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t11ActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(empname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(empid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(542, 542, 542))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(contactno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(gender, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(age, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                                .addGap(217, 217, 217)
                                .addComponent(t3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(empaddress)
                                    .addComponent(empemail, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(218, 218, 218)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t1)
                                    .addComponent(t2)
                                    .addComponent(t4)
                                    .addComponent(t5)
                                    .addComponent(t6)
                                    .addComponent(t7)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jobposition)
                                    .addComponent(hiredate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stationid, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(218, 218, 218)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(t11)
                                        .addGap(1, 1, 1))
                                    .addComponent(t9)
                                    .addComponent(t8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(update)
                .addGap(41, 41, 41)
                .addComponent(delete)
                .addGap(64, 64, 64)
                .addComponent(cancel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(age, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(t4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empemail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hiredate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jobposition, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stationid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(243, 243, 243))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactnoActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
       String url = "jdbc:mysql://localhost/railway";
String user = "root";
String pwd = "123456";

try {
    // 1. Get all input
    String empname = t2.getText().trim();
    String contactno = t3.getText().trim();
    int age = Integer.parseInt(t4.getText().trim());
    String gender = t5.getText().trim();
    String empaddress = t6.getText().trim();
    String empemail = t7.getText().trim();
    String hiredateStr = t8.getText().trim(); // yyyy-MM-dd
    String jobposition = t9.getText().trim();
    double salary = Double.parseDouble(t10.getText().trim());
    int stationid = Integer.parseInt(t11.getText().trim());

    // 2. Convert hire date
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    java.util.Date utilDate = sdf.parse(hiredateStr);
    java.sql.Date sqlHireDate = new java.sql.Date(utilDate.getTime());

    // 3. Connection
    Connection conn = DriverManager.getConnection(url, user, pwd);

    // 4. Check if employee already exists (based on email, which is UNIQUE)
    String checkQuery = "SELECT * FROM employees WHERE EMP_EMAIL = ?";
    PreparedStatement checkStmt = conn.prepareStatement(checkQuery);
    checkStmt.setString(1, empemail);
    ResultSet rs = checkStmt.executeQuery();

    if (rs.next()) {
        JOptionPane.showMessageDialog(this, "Employee with this email already exists.");
    } else {
        // 5. Insert new employee (auto EMP_ID)
        String insertQuery = "INSERT INTO employees (EMP_NAME, CONTACT_NO, AGE, GENDER, EMP_ADDRESS, EMP_EMAIL, HIRE_DATE, JOB_POSITION, SALARY, STATION_ID) "
                           + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement insertStmt = conn.prepareStatement(insertQuery);
        insertStmt.setString(1, empname);
        insertStmt.setString(2, contactno);
        insertStmt.setInt(3, age);
        insertStmt.setString(4, gender);
        insertStmt.setString(5, empaddress);
        insertStmt.setString(6, empemail);
        insertStmt.setDate(7, sqlHireDate);
        insertStmt.setString(8, jobposition);
        insertStmt.setDouble(9, salary);
        insertStmt.setInt(10, stationid);

        insertStmt.executeUpdate();
        JOptionPane.showMessageDialog(this, "Employee added successfully.");
        insertStmt.close();
    }

    // Cleanup
    rs.close();
    checkStmt.close();
    conn.close();

    // Clear fields
    t1.setText(""); // optional if you're showing EMP_ID
    t2.setText(""); t3.setText(""); t4.setText(""); t5.setText("");
    t6.setText(""); t7.setText(""); t8.setText(""); t9.setText("");
    t10.setText(""); t11.setText("");

} catch (ParseException pe) {
    JOptionPane.showMessageDialog(this, "Invalid date format (use yyyy-MM-dd).");
} catch (NumberFormatException nfe) {
    JOptionPane.showMessageDialog(this, "Invalid number format.");
} catch (SQLException sqle) {
    JOptionPane.showMessageDialog(this, "SQL Error: " + sqle.getMessage());
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    e.printStackTrace();
}
  

        
    }//GEN-LAST:event_addActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8ActionPerformed

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t9ActionPerformed

    private void t10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t10ActionPerformed

    private void t11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t11ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:

    String url = "jdbc:mysql://localhost/railway";
    String user = "root";
    String pwd = "123456";

    try {
        // 1. Get all input
        int empid = Integer.parseInt(t1.getText().trim());
        String empname = t2.getText().trim();
        String contactno = t3.getText().trim();
        int age = Integer.parseInt(t4.getText().trim());
        String gender = t5.getText().trim();
        String empaddress = t6.getText().trim();
        String empemail = t7.getText().trim();
        String hiredateStr = t8.getText().trim(); // yyyy-MM-dd
        String jobposition = t9.getText().trim();
        double salary = Double.parseDouble(t10.getText().trim());
        int stationid = Integer.parseInt(t11.getText().trim());

        // 2. Convert hire date
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date utilDate = sdf.parse(hiredateStr);
        java.sql.Date sqlHireDate = new java.sql.Date(utilDate.getTime());

        // 3. Connection
        Connection conn = DriverManager.getConnection(url, user, pwd);

        // 4. Check if employee exists by ID
        String checkQuery = "SELECT * FROM employees WHERE EMP_ID = ?";
        PreparedStatement checkStmt = conn.prepareStatement(checkQuery);
        checkStmt.setInt(1, empid);
        ResultSet rs = checkStmt.executeQuery();

        if (!rs.next()) {
            JOptionPane.showMessageDialog(this, "Employee ID not found.");
        } else {
            // 5. Update query
            String updateQuery = "UPDATE employees SET EMP_NAME=?, CONTACT_NO=?, AGE=?, GENDER=?, EMP_ADDRESS=?, EMP_EMAIL=?, HIRE_DATE=?, JOB_POSITION=?, SALARY=?, STATION_ID=? WHERE EMP_ID=?";
            PreparedStatement updateStmt = conn.prepareStatement(updateQuery);

            updateStmt.setString(1, empname);
            updateStmt.setString(2, contactno);
            updateStmt.setInt(3, age);
            updateStmt.setString(4, gender);
            updateStmt.setString(5, empaddress);
            updateStmt.setString(6, empemail);
            updateStmt.setDate(7, sqlHireDate);
            updateStmt.setString(8, jobposition);
            updateStmt.setDouble(9, salary);
            updateStmt.setInt(10, stationid);
            updateStmt.setInt(11, empid);

            int rowsAffected = updateStmt.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Employee updated successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Update failed.");
            }

            updateStmt.close();
        }

        rs.close();
        checkStmt.close();
        conn.close();

    } catch (ParseException pe) {
        JOptionPane.showMessageDialog(this, "Invalid date format (use yyyy-MM-dd).");
    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(this, "Invalid number format.");
    } catch (SQLException sqle) {
        JOptionPane.showMessageDialog(this, "SQL Error: " + sqle.getMessage());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }


    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
       
   
    String url = "jdbc:mysql://localhost/railway";
    String user = "root";
    String pwd = "123456";

    try {
        int empid = Integer.parseInt(t1.getText().trim());

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete employee with ID: " + empid + "?",
                "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        Connection conn = DriverManager.getConnection(url, user, pwd);

        // Check if employee exists
        String checkQuery = "SELECT * FROM employees WHERE EMP_ID = ?";
        PreparedStatement checkStmt = conn.prepareStatement(checkQuery);
        checkStmt.setInt(1, empid);
        ResultSet rs = checkStmt.executeQuery();

        if (!rs.next()) {
            JOptionPane.showMessageDialog(this, "Employee with ID " + empid + " does not exist.");
        } else {
            // Delete from work_on
            String deleteWorkOnQuery = "DELETE FROM work_on WHERE EMP_ID = ?";
            PreparedStatement deleteWorkOnStmt = conn.prepareStatement(deleteWorkOnQuery);
            deleteWorkOnStmt.setInt(1, empid);
            deleteWorkOnStmt.executeUpdate();
            deleteWorkOnStmt.close();

            // Delete from shift
            String deleteShiftQuery = "DELETE FROM shift WHERE EMP_ID = ?";
            PreparedStatement deleteShiftStmt = conn.prepareStatement(deleteShiftQuery);
            deleteShiftStmt.setInt(1, empid);
            deleteShiftStmt.executeUpdate();
            deleteShiftStmt.close();

            // Delete from employees
            String deleteEmpQuery = "DELETE FROM employees WHERE EMP_ID = ?";
            PreparedStatement deleteEmpStmt = conn.prepareStatement(deleteEmpQuery);
            deleteEmpStmt.setInt(1, empid);
            int rowsAffected = deleteEmpStmt.executeUpdate();
            deleteEmpStmt.close();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Employee deleted successfully.");

                // Clear all fields
                t1.setText(""); t2.setText(""); t3.setText(""); t4.setText(""); t5.setText("");
                t6.setText(""); t7.setText(""); t8.setText(""); t9.setText(""); t10.setText(""); t11.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Deletion failed.");
            }
        }

        rs.close();
        checkStmt.close();
        conn.close();

    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(this, "Invalid EMP ID.");
    } catch (SQLException sqle) {
        JOptionPane.showMessageDialog(this, "SQL Error: " + sqle.getMessage());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }



    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton age;
    private javax.swing.JButton cancel;
    private javax.swing.JButton contactno;
    private javax.swing.JButton delete;
    private javax.swing.JButton empaddress;
    private javax.swing.JButton empemail;
    private javax.swing.JButton empid;
    private javax.swing.JButton empname;
    private javax.swing.JButton gender;
    private javax.swing.JButton hiredate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jobposition;
    private javax.swing.JButton salary;
    private javax.swing.JButton stationid;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
